# Generated by Django 3.1 on 2022-04-13 01:23

import concours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('candidat_id', models.AutoField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('lycee', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('genie', models.CharField(max_length=100)),
                ('centre', models.CharField(max_length=100)),
                ('moy_seconde', models.FloatField(default=0)),
                ('moy_premiere', models.FloatField(default=0)),
                ('moy_terminale', models.FloatField(default=0)),
                ('moy_bac', models.FloatField(default=0)),
                ('moy_concours', models.FloatField(default=0)),
                ('moy_general', models.FloatField(default=concours.models.Candidat.get_moy_general)),
            ],
            options={
                'ordering': ('moy_general',),
            },
        ),
    ]
