# Generated by Django 3.1 on 2022-04-13 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidat',
            options={},
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='moy_general',
        ),
    ]
